# Import relevant libraries

In [1]:
import numpy as np

# Dot product

In [2]:
x = np.array([2, 8, -4])
y = np.array([1, -7, 3])

In [3]:
np.dot(x, y)

-66

In [4]:
u = np.array([0, 2, 5, 8])
v = np.array([20, 3, 4, -1])

In [5]:
np.dot(u, v)

18

# Scalar * Scalar

In [6]:
np.dot(5, 6)

30

In [7]:
np.dot(10, -2)

-20

# Scalar * Vector

In [8]:
x

array([ 2,  8, -4])

In [9]:
5 * x

array([ 10,  40, -20])

In [10]:
np.dot(5, x)

array([ 10,  40, -20])

# Scalar * Matrix

In [11]:
A = np.array([[5, 12, 6], [-3, 0, 14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [12]:
3 * A

array([[15, 36, 18],
       [-9,  0, 42]])

# Matrix * Matrix

## Example 1

In [15]:
B = np.array([[2, -1], [8, 0], [3, 0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [16]:
np.dot(A, B)

array([[124,  -5],
       [ 36,   3]])

## Example 2

In [17]:
C = np.array([[-12, 5, -5, 1, 6], [6, -2, 0, 0, 3], [10, 2, 0, 8, 0], [9, -4, 8, 3, -6]])
C

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,   3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [18]:
D = np.array([[6, -1], [8, -4], [2, -2], [7, 4], [-6, -9]])
D

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [19]:
np.dot(C, D)

array([[-71, -48],
       [  2, -25],
       [132,  14],
       [ 95,  57]])