# Import the relevant libraries

In [1]:
import numpy as np

## Addition

### Addition of scalars

In [2]:
5 + 5

10

In [3]:
10 - 4

6

### Addition of matrices

In [4]:
m1 = np.array([[5, 12, 6], [-3, 0, -14]])
m1

array([[  5,  12,   6],
       [ -3,   0, -14]])

In [6]:
m3 = np.array([[5, 3], [-2, 4]])
m3

array([[ 5,  3],
       [-2,  4]])

In [8]:
m1 + m3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

## Addition of vectors

In [9]:
v1 = np.array([1, 2, 3, 4, 5])
v1

array([1, 2, 3, 4, 5])

In [10]:
v3 = np.array([1, 2, 3])
v3

array([1, 2, 3])

In [11]:
v1 + v3

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

## Exceptions (addition with a scalar)

In [12]:
m1

array([[  5,  12,   6],
       [ -3,   0, -14]])

In [13]:
m1 + 1

array([[  6,  13,   7],
       [ -2,   1, -13]])

In [14]:
v1

array([1, 2, 3, 4, 5])

In [15]:
v1 + 1

array([2, 3, 4, 5, 6])

In [16]:
m1 + np.array([1])

array([[  6,  13,   7],
       [ -2,   1, -13]])