# Multiple Linear Regression with sklearn - Exercise Solution

You are given a real estate dataset. 

Real estate is one of those examples that every regression course goes through as it is extremely easy to understand and there is a (almost always) certain causal relationship to be found.

The data is located in the file: 'real_estate_price_size_year.csv'. 

You are expected to create a multiple linear regression (similar to the one in the lecture), using the new data. 

Apart from that, please:
-  Display the intercept and coefficient(s)
-  Find the R-squared and Adjusted R-squared
-  Compare the R-squared and the Adjusted R-squared
-  Compare the R-squared of this regression and the simple linear regression where only 'size' was used
-  Using the model make a prediction about an apartment with size 750 sq.ft. from 2009
-  Find the univariate (or multivariate if you wish - see the article) p-values of the two variables. What can you say about them?
-  Create a summary table with your findings

In this exercise, the dependent variable is 'price', while the independent variables are 'size' and 'year'.

Good luck!

## Import the relevant libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression
import seaborn as sns
sns.set()

## Load the data

In [2]:
data = pd.read_csv('real_estate_price_size_year.csv')

In [3]:
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

## Create the regression

### Declare the dependent and the independent variables

In [4]:
x = data[['size', 'year']]
y = data['price']

### Regression

In [5]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

### Find the intercept

In [6]:
reg.intercept_

-5772267.017463277

### Find the coefficients

In [7]:
reg.coef_

array([ 227.70085401, 2916.78532684])

### Calculate the R-squared

In [8]:
reg.score(x,y)

0.7764803683276793

### Calculate the Adjusted R-squared

In [10]:
n = x.shape[0]
k = x.shape[1]
adj_r2 = 1-((1-reg.score(x,y)) * (n - 1) / (n - k - 1))

In [11]:
adj_r2

0.77187171612825

### Compare the R-squared and the Adjusted R-squared

Answer...

### Compare the Adjusted R-squared with the R-squared of the simple linear regression

Answer...

### Making predictions

Find the predicted price of an apartment that has a size of 750 sq.ft. from 2009.

In [12]:
new_data = [[750, 2009]]
reg.predict(new_data)

C:\Users\johan\AppData\Roaming\Python\Python37\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([258330.34465995])

### Calculate the univariate p-values of the variables

In [13]:
freg = f_regression(x,y)

In [14]:
p = freg[1]

In [16]:
p.round(3)

array([0.   , 0.357])

### Create a summary table with your findings

In [21]:
summary = pd.DataFrame(data=[['Size',reg.coef_[0]],['Year', reg.coef_[1]]], columns=[['Features', 'Coefficient']])
summary

Features  Coefficient
0     Size   227.700854
1     Year  2916.785327

In [23]:
summary['p-values'] = p.round(3)
summary

Features  Coefficient p-values
0     Size   227.700854    0.000
1     Year  2916.785327    0.357